default:
	g++ -std=c++17 -O3 \
	MatrixChainMultiplication.cpp -o ./MatrixChainMultiplication \
	&& \
	cat input.txt \
	&& \
	time ./MatrixChainMultiplication <input.txt \
	&& \
	rm ./MatrixChainMultiplication
